CREATE TABLE "identity_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"full_name" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"age" integer NOT NULL,
	"date_of_birth" text NOT NULL,
	"birth_gender" text NOT NULL,
	"gender_identity" text NOT NULL,
	"pronouns" text NOT NULL,
	"sexual_orientation" text NOT NULL,
	"ethnicity" text NOT NULL,
	"nationality" text NOT NULL,
	"spoken_languages" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"address" text NOT NULL,
	"city" text NOT NULL,
	"state" text,
	"zip_code" text NOT NULL,
	"country" text NOT NULL,
	"citizenship_status" text NOT NULL,
	"height" text NOT NULL,
	"weight" text NOT NULL,
	"build" text NOT NULL,
	"hair_color" text NOT NULL,
	"eye_color" text NOT NULL,
	"skin_tone" text NOT NULL,
	"body_measurements" text NOT NULL,
	"job_title" text NOT NULL,
	"company" text NOT NULL,
	"industry" text NOT NULL,
	"annual_income" text NOT NULL,
	"marital_status" text NOT NULL,
	"spouse_name" text,
	"linkedin_url" text NOT NULL,
	"twitter_url" text NOT NULL,
	"instagram_url" text NOT NULL,
	"github_url" text NOT NULL,
	"onlyfans_url" text NOT NULL,
	"dating_url" text NOT NULL,
	"facebook_url" text NOT NULL,
	"tiktok_url" text NOT NULL,
	"youtube_url" text NOT NULL,
	"discord_url" text NOT NULL,
	"reddit_url" text NOT NULL,
	"snapchat_url" text NOT NULL,
	"blood_type" text NOT NULL,
	"medical_conditions" text NOT NULL,
	"bank_name" text NOT NULL,
	"account_type" text NOT NULL,
	"routing_number" text NOT NULL,
	"credit_score" text NOT NULL,
	"credit_card_number" text NOT NULL,
	"credit_card_type" text NOT NULL,
	"credit_card_expiry" text NOT NULL,
	"credit_card_cvv" text NOT NULL,
	"criminal_record" text NOT NULL,
	"criminal_history" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
